import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

from app.cleaning.config import config
from app.cleaning.pipeline import DataCleaningPipeline
from app.core.execution_context import ExecutionContext
from app.core.pipeline_manager import PipelineManager
from app.eda.eda_pipeline import EDAPipeline


logger = logging.getLogger(__name__)


class AnalyticsPipeline:
    """Unified end-to-end analytics pipeline orchestrator."""

    def __init__(
        self,
        raw_file_path: Optional[Path] = None,
        cleaned_file_path: Optional[Path] = None,
    ):
        self.context = ExecutionContext(
            raw_data_file=raw_file_path or config.RAW_DATA_FILE,
            cleaned_data_file=cleaned_file_path or config.CLEANED_DATA_FILE,
            reports_dir=config.REPORTS_DIR,
            visualizations_dir=config.BASE_DIR / "visualizations",
        )
        self.manager = PipelineManager(self.context)
        self.cleaning_pipeline: Optional[DataCleaningPipeline] = None
        self.eda_pipeline: Optional[EDAPipeline] = None

    def run_cleaning_phase(self) -> Dict[str, Any]:
        logger.info("Starting unified pipeline cleaning phase")
        self.cleaning_pipeline = DataCleaningPipeline(
            raw_file_path=self.context.raw_data_file,
            output_file_path=self.context.cleaned_data_file,
        )
        self.context.cleaning_results = self.cleaning_pipeline.run()
        return self.context.cleaning_results

    def run_validation_phase(self) -> Dict[str, Any]:
        return self.context.cleaning_results.get("validation_stats", {})

    def run_profiling_phase(self) -> Dict[str, Any]:
        if not self.eda_pipeline or not self.eda_pipeline.profiler:
            return {}
        return self.eda_pipeline.profiler.get_profile()

    def run_eda_phase(self) -> Dict[str, Any]:
        logger.info("Starting unified pipeline EDA phase")
        self.eda_pipeline = EDAPipeline(data_file_path=self.context.cleaned_data_file)
        self.context.eda_results = self.eda_pipeline.run()
        return self.context.eda_results

    def run_reporting_phase(self) -> Path:
        self.manager.refresh_generated_outputs()
        return self.generate_final_pipeline_report()

    def run_visualization_phase(self) -> list[Path]:
        self.manager.refresh_generated_outputs()
        return self.context.generated_visualizations

    def run(self) -> ExecutionContext:
        logger.info("=" * 80)
        logger.info("UNIFIED ANALYTICS PIPELINE - EXECUTION STARTED")
        logger.info("=" * 80)
        self.manager.ensure_output_directories()

        try:
            self.run_cleaning_phase()
            self.run_eda_phase()
            self.context.finish()
            self.run_visualization_phase()
            self.run_reporting_phase()
            logger.info("Unified analytics pipeline completed successfully")
            return self.context
        except Exception:
            self.context.finish()
            logger.exception("Unified analytics pipeline failed")
            raise

    def generate_final_pipeline_report(self) -> Path:
        report_path = self.context.reports_dir / "final_pipeline_report.txt"
        cleaning = self.context.cleaning_results
        eda = self.context.eda_results

        lines = [
            "=" * 80,
            "FINAL ANALYTICS PIPELINE REPORT",
            "=" * 80,
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"Pipeline Start Time: {self.context.start_time.isoformat()}",
            f"Pipeline End Time: {(self.context.end_time or datetime.now()).isoformat()}",
            f"Execution Duration: {self.context.duration_seconds:.2f} seconds",
            "",
            "CURRENT ARCHITECTURE",
            "-" * 80,
            "The application now uses app.main as the single entry point. It delegates",
            "to app.core.orchestrator.AnalyticsPipeline, which coordinates the existing",
            "cleaning pipeline and EDA pipeline without rewriting their working logic.",
            "",
            "ARCHITECTURAL ISSUES IDENTIFIED",
            "-" * 80,
            "1. Multiple phase-level entry responsibilities existed in main.py and EDA.",
            "2. Several EDA modules referenced undefined BASE_DIR output paths.",
            "3. Cleaned data used an Excel default path while always writing CSV format.",
            "4. Reporting and visualization outputs were generated by phase modules but",
            "   not collected into one final execution summary.",
            "5. EDA package files were untracked in git at analysis time.",
            "",
            "RECOMMENDATIONS",
            "-" * 80,
            "1. Keep analyzers focused on one analysis concern and keep orchestration in core/.",
            "2. Move future thresholds and column groups into config rather than hardcoding.",
            "3. Add unit tests for analyzers and an integration test for python -m app.main.",
            "4. Consider replacing text reports with structured JSON plus rendered summaries.",
            "",
            "CLEANING SUMMARY",
            "-" * 80,
            f"Status: {cleaning.get('status', 'N/A')}",
            f"Raw Rows: {cleaning.get('raw_rows', 0):,}",
            f"Cleaned Rows: {cleaning.get('cleaned_rows', 0):,}",
            f"Rows Removed: {cleaning.get('rows_removed', 0):,}",
            f"Clean Dataset: {cleaning.get('output_file', self.context.cleaned_data_file)}",
            f"Cleaning Stats: {cleaning.get('cleaning_stats', {})}",
            f"Validation Stats: {cleaning.get('validation_stats', {})}",
            "",
            "EDA SUMMARY",
            "-" * 80,
            f"Status: {eda.get('status', 'N/A')}",
            f"Rows Analyzed: {eda.get('rows_analyzed', 0):,}",
            f"Columns Analyzed: {eda.get('columns_analyzed', 0):,}",
            f"EDA Duration: {eda.get('duration_seconds', 0):.2f} seconds",
            "",
            "GENERATED REPORTS",
            "-" * 80,
        ]

        lines.extend(f"- {path}" for path in self.context.generated_reports)
        lines.extend([
            "",
            "GENERATED VISUALIZATIONS",
            "-" * 80,
        ])
        lines.extend(f"- {path}" for path in self.context.generated_visualizations)

        lines.extend([
            "",
            "BUSINESS INSIGHTS SUMMARY",
            "-" * 80,
            "See reports/eda/business_insights.txt and reports/eda/executive_summary.txt",
            "for detailed revenue, customer, order, payment, and referral insights.",
            "",
            "=" * 80,
            "END OF FINAL ANALYTICS PIPELINE REPORT",
            "=" * 80,
        ])

        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text("\n".join(lines), encoding=config.ENCODING)
        self.manager.refresh_generated_outputs()
        return report_path
